/********************************************************************************
** Form generated from reading UI file 'insur_guaranteeslip.ui'
**
** Created by: Qt User Interface Compiler version 5.11.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_INSUR_GUARANTEESLIP_H
#define UI_INSUR_GUARANTEESLIP_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Form
{
public:
    QLabel *INSUR_LABEL;
    QLabel *label_2;
    QDateEdit *InsuranceStartDate;
    QLabel *label_3;
    QDateEdit *InsuranceEndDate;
    QLabel *label_4;
    QComboBox *InsuranceCompany;
    QLabel *label_5;
    QLineEdit *CommercialRiskCode;
    QLabel *label_6;
    QLineEdit *TrafficRiskCode;
    QLabel *label_7;
    QLineEdit *Contacts;
    QLabel *label_8;
    QLineEdit *Telephone;
    QLineEdit *IdCard;
    QLabel *label_9;
    QLabel *label_10;
    QComboBox *Agent;
    QLineEdit *Department;
    QLabel *label_11;
    QLabel *label_12;
    QComboBox *PaymentState;
    QLabel *label_13;
    QDateEdit *InsurancePaymentDate;
    QComboBox *PaymentMethod;
    QLabel *label_14;
    QLineEdit *TotalPremium;
    QLabel *label_15;
    QLineEdit *TotalCommercialPremium;
    QLabel *label_16;
    QLabel *label_17;
    QLineEdit *GrossPremium;
    QLineEdit *StrongPreferenceRatio;
    QLabel *label_18;
    QLineEdit *CommercialPreferenceRatio;
    QLabel *label_19;
    QLabel *label_20;
    QLineEdit *ChiuQiangShouldBeCharged;
    QLabel *label_21;
    QLineEdit *CommercialCharges;
    QLineEdit *TotalReceivable;
    QLabel *label_22;
    QLineEdit *CommissionCost;
    QLabel *label_23;
    QTabWidget *tabWidget;
    QWidget *tab;
    QLineEdit *CarOwner;
    QLabel *label_24;
    QLineEdit *PlateNumber;
    QLabel *label_25;
    QLineEdit *FrameNumber;
    QLabel *label_26;
    QLineEdit *MotorcycleType;
    QLabel *label_27;
    QLineEdit *EngineNumber;
    QLabel *label_28;
    QLineEdit *PolicyHolder;
    QLabel *label_29;
    QLineEdit *CarBrand;
    QLabel *label_30;
    QLineEdit *SeatingNumber;
    QLabel *label_31;
    QLineEdit *InsurancedPerson;
    QLabel *label_32;
    QDateEdit *SalesDate;
    QLabel *label_33;
    QLineEdit *NewCarPurchasePrice;
    QLabel *label_34;
    QLabel *label_35;
    QLineEdit *Description;
    QWidget *tab_2;
    QLabel *label_36;
    QLineEdit *VehicleLossInsurance;
    QLineEdit *InsurancePremiumPorLossOfVehicle;
    QLabel *label_37;
    QLineEdit *ThirdPartyLiabilityCoverage;
    QLineEdit *ThirdPartyLiabilityInsurancePremium;
    QLineEdit *SpontaneousCombustionLossInsurance;
    QLabel *label_38;
    QLineEdit *SpontaneousCombustionLossInsurancePremium;
    QLineEdit *ScarInsuranceAmount;
    QLabel *label_39;
    QLineEdit *ScarInsurancePremium;
    QLineEdit *InsuranceCoverage;
    QLabel *label_40;
    QLineEdit *PremiumInsurancePremium;
    QLineEdit *Description_2;
    QLabel *label_41;
    QPushButton *Entry;
    QPushButton *Cancel;

    void setupUi(QWidget *Form)
    {
        if (Form->objectName().isEmpty())
            Form->setObjectName(QStringLiteral("Form"));
        Form->resize(800, 650);
        INSUR_LABEL = new QLabel(Form);
        INSUR_LABEL->setObjectName(QStringLiteral("INSUR_LABEL"));
        INSUR_LABEL->setGeometry(QRect(220, 0, 360, 60));
        QFont font;
        font.setPointSize(30);
        font.setBold(true);
        font.setWeight(75);
        font.setKerning(true);
        INSUR_LABEL->setFont(font);
        INSUR_LABEL->setAlignment(Qt::AlignCenter);
        label_2 = new QLabel(Form);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(30, 80, 60, 25));
        InsuranceStartDate = new QDateEdit(Form);
        InsuranceStartDate->setObjectName(QStringLiteral("InsuranceStartDate"));
        InsuranceStartDate->setGeometry(QRect(90, 80, 110, 25));
        label_3 = new QLabel(Form);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(280, 80, 60, 25));
        InsuranceEndDate = new QDateEdit(Form);
        InsuranceEndDate->setObjectName(QStringLiteral("InsuranceEndDate"));
        InsuranceEndDate->setGeometry(QRect(340, 80, 110, 25));
        InsuranceEndDate->setTimeSpec(Qt::LocalTime);
        label_4 = new QLabel(Form);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(540, 80, 60, 25));
        InsuranceCompany = new QComboBox(Form);
        InsuranceCompany->setObjectName(QStringLiteral("InsuranceCompany"));
        InsuranceCompany->setGeometry(QRect(600, 80, 160, 25));
        label_5 = new QLabel(Form);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(30, 120, 60, 25));
        CommercialRiskCode = new QLineEdit(Form);
        CommercialRiskCode->setObjectName(QStringLiteral("CommercialRiskCode"));
        CommercialRiskCode->setGeometry(QRect(90, 120, 250, 25));
        CommercialRiskCode->setInputMethodHints(Qt::ImhNone);
        label_6 = new QLabel(Form);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(450, 120, 60, 25));
        TrafficRiskCode = new QLineEdit(Form);
        TrafficRiskCode->setObjectName(QStringLiteral("TrafficRiskCode"));
        TrafficRiskCode->setGeometry(QRect(510, 120, 250, 25));
        TrafficRiskCode->setInputMethodHints(Qt::ImhNone);
        label_7 = new QLabel(Form);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(30, 160, 60, 25));
        label_7->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Contacts = new QLineEdit(Form);
        Contacts->setObjectName(QStringLiteral("Contacts"));
        Contacts->setGeometry(QRect(90, 160, 110, 25));
        Contacts->setInputMethodHints(Qt::ImhNone);
        label_8 = new QLabel(Form);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(280, 160, 60, 25));
        label_8->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Telephone = new QLineEdit(Form);
        Telephone->setObjectName(QStringLiteral("Telephone"));
        Telephone->setGeometry(QRect(340, 160, 110, 25));
        Telephone->setInputMethodHints(Qt::ImhNone);
        IdCard = new QLineEdit(Form);
        IdCard->setObjectName(QStringLiteral("IdCard"));
        IdCard->setGeometry(QRect(600, 160, 160, 25));
        IdCard->setInputMethodHints(Qt::ImhNone);
        label_9 = new QLabel(Form);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(540, 160, 60, 25));
        label_9->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_10 = new QLabel(Form);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(30, 200, 60, 25));
        label_10->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Agent = new QComboBox(Form);
        Agent->setObjectName(QStringLiteral("Agent"));
        Agent->setGeometry(QRect(90, 200, 110, 25));
        Department = new QLineEdit(Form);
        Department->setObjectName(QStringLiteral("Department"));
        Department->setEnabled(false);
        Department->setGeometry(QRect(340, 200, 110, 25));
        Department->setInputMethodHints(Qt::ImhNone);
        label_11 = new QLabel(Form);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(280, 200, 60, 25));
        label_11->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_12 = new QLabel(Form);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(540, 200, 60, 25));
        PaymentState = new QComboBox(Form);
        PaymentState->addItem(QString());
        PaymentState->addItem(QString());
        PaymentState->setObjectName(QStringLiteral("PaymentState"));
        PaymentState->setGeometry(QRect(600, 200, 160, 25));
        PaymentState->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_13 = new QLabel(Form);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(30, 240, 60, 25));
        InsurancePaymentDate = new QDateEdit(Form);
        InsurancePaymentDate->setObjectName(QStringLiteral("InsurancePaymentDate"));
        InsurancePaymentDate->setGeometry(QRect(90, 240, 110, 25));
        PaymentMethod = new QComboBox(Form);
        PaymentMethod->addItem(QString());
        PaymentMethod->addItem(QString());
        PaymentMethod->addItem(QString());
        PaymentMethod->addItem(QString());
        PaymentMethod->setObjectName(QStringLiteral("PaymentMethod"));
        PaymentMethod->setGeometry(QRect(340, 240, 110, 25));
        PaymentMethod->setContextMenuPolicy(Qt::DefaultContextMenu);
        label_14 = new QLabel(Form);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(280, 240, 60, 25));
        TotalPremium = new QLineEdit(Form);
        TotalPremium->setObjectName(QStringLiteral("TotalPremium"));
        TotalPremium->setEnabled(false);
        TotalPremium->setGeometry(QRect(600, 240, 160, 25));
        TotalPremium->setInputMethodHints(Qt::ImhNone);
        label_15 = new QLabel(Form);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(540, 240, 60, 25));
        label_15->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        TotalCommercialPremium = new QLineEdit(Form);
        TotalCommercialPremium->setObjectName(QStringLiteral("TotalCommercialPremium"));
        TotalCommercialPremium->setEnabled(false);
        TotalCommercialPremium->setGeometry(QRect(90, 280, 110, 25));
        TotalCommercialPremium->setInputMethodHints(Qt::ImhNone);
        label_16 = new QLabel(Form);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(30, 280, 60, 25));
        label_16->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_17 = new QLabel(Form);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(280, 280, 60, 25));
        label_17->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        GrossPremium = new QLineEdit(Form);
        GrossPremium->setObjectName(QStringLiteral("GrossPremium"));
        GrossPremium->setEnabled(false);
        GrossPremium->setGeometry(QRect(340, 280, 110, 25));
        GrossPremium->setInputMethodHints(Qt::ImhNone);
        StrongPreferenceRatio = new QLineEdit(Form);
        StrongPreferenceRatio->setObjectName(QStringLiteral("StrongPreferenceRatio"));
        StrongPreferenceRatio->setEnabled(true);
        StrongPreferenceRatio->setGeometry(QRect(600, 280, 30, 25));
        StrongPreferenceRatio->setInputMethodHints(Qt::ImhNone);
        label_18 = new QLabel(Form);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(540, 280, 60, 25));
        label_18->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        CommercialPreferenceRatio = new QLineEdit(Form);
        CommercialPreferenceRatio->setObjectName(QStringLiteral("CommercialPreferenceRatio"));
        CommercialPreferenceRatio->setEnabled(true);
        CommercialPreferenceRatio->setGeometry(QRect(730, 280, 30, 25));
        CommercialPreferenceRatio->setInputMethodHints(Qt::ImhNone);
        label_19 = new QLabel(Form);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(670, 280, 60, 25));
        label_19->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_20 = new QLabel(Form);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(30, 320, 60, 25));
        label_20->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ChiuQiangShouldBeCharged = new QLineEdit(Form);
        ChiuQiangShouldBeCharged->setObjectName(QStringLiteral("ChiuQiangShouldBeCharged"));
        ChiuQiangShouldBeCharged->setEnabled(false);
        ChiuQiangShouldBeCharged->setGeometry(QRect(90, 320, 110, 25));
        ChiuQiangShouldBeCharged->setInputMethodHints(Qt::ImhNone);
        label_21 = new QLabel(Form);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(280, 320, 60, 25));
        label_21->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        CommercialCharges = new QLineEdit(Form);
        CommercialCharges->setObjectName(QStringLiteral("CommercialCharges"));
        CommercialCharges->setEnabled(false);
        CommercialCharges->setGeometry(QRect(340, 320, 110, 25));
        CommercialCharges->setInputMethodHints(Qt::ImhNone);
        TotalReceivable = new QLineEdit(Form);
        TotalReceivable->setObjectName(QStringLiteral("TotalReceivable"));
        TotalReceivable->setEnabled(false);
        TotalReceivable->setGeometry(QRect(600, 320, 160, 25));
        TotalReceivable->setInputMethodHints(Qt::ImhNone);
        label_22 = new QLabel(Form);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(540, 320, 60, 25));
        label_22->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        CommissionCost = new QLineEdit(Form);
        CommissionCost->setObjectName(QStringLiteral("CommissionCost"));
        CommissionCost->setEnabled(false);
        CommissionCost->setGeometry(QRect(600, 360, 160, 25));
        CommissionCost->setInputMethodHints(Qt::ImhNone);
        label_23 = new QLabel(Form);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(540, 360, 60, 25));
        label_23->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        tabWidget = new QTabWidget(Form);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(30, 380, 730, 200));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        CarOwner = new QLineEdit(tab);
        CarOwner->setObjectName(QStringLiteral("CarOwner"));
        CarOwner->setGeometry(QRect(70, 10, 130, 25));
        CarOwner->setInputMethodHints(Qt::ImhNone);
        label_24 = new QLabel(tab);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(10, 10, 60, 25));
        label_24->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        PlateNumber = new QLineEdit(tab);
        PlateNumber->setObjectName(QStringLiteral("PlateNumber"));
        PlateNumber->setGeometry(QRect(310, 10, 130, 25));
        PlateNumber->setInputMethodHints(Qt::ImhNone);
        label_25 = new QLabel(tab);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(250, 10, 60, 25));
        label_25->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        FrameNumber = new QLineEdit(tab);
        FrameNumber->setObjectName(QStringLiteral("FrameNumber"));
        FrameNumber->setGeometry(QRect(550, 10, 130, 25));
        FrameNumber->setInputMethodHints(Qt::ImhNone);
        label_26 = new QLabel(tab);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(490, 10, 60, 25));
        label_26->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        MotorcycleType = new QLineEdit(tab);
        MotorcycleType->setObjectName(QStringLiteral("MotorcycleType"));
        MotorcycleType->setGeometry(QRect(70, 40, 130, 25));
        MotorcycleType->setInputMethodHints(Qt::ImhNone);
        label_27 = new QLabel(tab);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(10, 40, 60, 25));
        label_27->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        EngineNumber = new QLineEdit(tab);
        EngineNumber->setObjectName(QStringLiteral("EngineNumber"));
        EngineNumber->setGeometry(QRect(310, 40, 130, 25));
        EngineNumber->setInputMethodHints(Qt::ImhNone);
        label_28 = new QLabel(tab);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(250, 40, 60, 25));
        label_28->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        PolicyHolder = new QLineEdit(tab);
        PolicyHolder->setObjectName(QStringLiteral("PolicyHolder"));
        PolicyHolder->setGeometry(QRect(550, 40, 130, 25));
        PolicyHolder->setInputMethodHints(Qt::ImhNone);
        label_29 = new QLabel(tab);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(490, 40, 60, 25));
        label_29->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        CarBrand = new QLineEdit(tab);
        CarBrand->setObjectName(QStringLiteral("CarBrand"));
        CarBrand->setGeometry(QRect(70, 70, 130, 25));
        CarBrand->setInputMethodHints(Qt::ImhNone);
        label_30 = new QLabel(tab);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(10, 70, 60, 25));
        label_30->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        SeatingNumber = new QLineEdit(tab);
        SeatingNumber->setObjectName(QStringLiteral("SeatingNumber"));
        SeatingNumber->setGeometry(QRect(310, 70, 130, 25));
        SeatingNumber->setInputMethodHints(Qt::ImhNone);
        label_31 = new QLabel(tab);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(250, 70, 60, 25));
        label_31->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        InsurancedPerson = new QLineEdit(tab);
        InsurancedPerson->setObjectName(QStringLiteral("InsurancedPerson"));
        InsurancedPerson->setGeometry(QRect(550, 70, 130, 25));
        InsurancedPerson->setInputMethodHints(Qt::ImhNone);
        label_32 = new QLabel(tab);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(490, 70, 60, 25));
        label_32->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        SalesDate = new QDateEdit(tab);
        SalesDate->setObjectName(QStringLiteral("SalesDate"));
        SalesDate->setGeometry(QRect(70, 100, 130, 25));
        label_33 = new QLabel(tab);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(10, 100, 60, 25));
        NewCarPurchasePrice = new QLineEdit(tab);
        NewCarPurchasePrice->setObjectName(QStringLiteral("NewCarPurchasePrice"));
        NewCarPurchasePrice->setGeometry(QRect(310, 100, 130, 25));
        NewCarPurchasePrice->setInputMethodHints(Qt::ImhNone);
        label_34 = new QLabel(tab);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(250, 100, 60, 25));
        label_34->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_35 = new QLabel(tab);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(10, 130, 60, 25));
        Description = new QLineEdit(tab);
        Description->setObjectName(QStringLiteral("Description"));
        Description->setGeometry(QRect(70, 130, 610, 25));
        Description->setInputMethodHints(Qt::ImhNone);
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        label_36 = new QLabel(tab_2);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(10, 10, 60, 25));
        label_36->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        VehicleLossInsurance = new QLineEdit(tab_2);
        VehicleLossInsurance->setObjectName(QStringLiteral("VehicleLossInsurance"));
        VehicleLossInsurance->setGeometry(QRect(70, 10, 110, 25));
        VehicleLossInsurance->setInputMethodHints(Qt::ImhNone);
        InsurancePremiumPorLossOfVehicle = new QLineEdit(tab_2);
        InsurancePremiumPorLossOfVehicle->setObjectName(QStringLiteral("InsurancePremiumPorLossOfVehicle"));
        InsurancePremiumPorLossOfVehicle->setGeometry(QRect(180, 10, 110, 25));
        InsurancePremiumPorLossOfVehicle->setInputMethodHints(Qt::ImhNone);
        label_37 = new QLabel(tab_2);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(410, 10, 60, 25));
        label_37->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ThirdPartyLiabilityCoverage = new QLineEdit(tab_2);
        ThirdPartyLiabilityCoverage->setObjectName(QStringLiteral("ThirdPartyLiabilityCoverage"));
        ThirdPartyLiabilityCoverage->setGeometry(QRect(470, 10, 110, 25));
        ThirdPartyLiabilityCoverage->setInputMethodHints(Qt::ImhNone);
        ThirdPartyLiabilityInsurancePremium = new QLineEdit(tab_2);
        ThirdPartyLiabilityInsurancePremium->setObjectName(QStringLiteral("ThirdPartyLiabilityInsurancePremium"));
        ThirdPartyLiabilityInsurancePremium->setGeometry(QRect(580, 10, 110, 25));
        ThirdPartyLiabilityInsurancePremium->setInputMethodHints(Qt::ImhNone);
        SpontaneousCombustionLossInsurance = new QLineEdit(tab_2);
        SpontaneousCombustionLossInsurance->setObjectName(QStringLiteral("SpontaneousCombustionLossInsurance"));
        SpontaneousCombustionLossInsurance->setGeometry(QRect(70, 50, 110, 25));
        SpontaneousCombustionLossInsurance->setInputMethodHints(Qt::ImhNone);
        label_38 = new QLabel(tab_2);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(10, 50, 60, 25));
        label_38->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        SpontaneousCombustionLossInsurancePremium = new QLineEdit(tab_2);
        SpontaneousCombustionLossInsurancePremium->setObjectName(QStringLiteral("SpontaneousCombustionLossInsurancePremium"));
        SpontaneousCombustionLossInsurancePremium->setGeometry(QRect(180, 50, 110, 25));
        SpontaneousCombustionLossInsurancePremium->setInputMethodHints(Qt::ImhNone);
        ScarInsuranceAmount = new QLineEdit(tab_2);
        ScarInsuranceAmount->setObjectName(QStringLiteral("ScarInsuranceAmount"));
        ScarInsuranceAmount->setGeometry(QRect(470, 50, 110, 25));
        ScarInsuranceAmount->setInputMethodHints(Qt::ImhNone);
        label_39 = new QLabel(tab_2);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(410, 50, 60, 25));
        label_39->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ScarInsurancePremium = new QLineEdit(tab_2);
        ScarInsurancePremium->setObjectName(QStringLiteral("ScarInsurancePremium"));
        ScarInsurancePremium->setGeometry(QRect(580, 50, 110, 25));
        ScarInsurancePremium->setInputMethodHints(Qt::ImhNone);
        InsuranceCoverage = new QLineEdit(tab_2);
        InsuranceCoverage->setObjectName(QStringLiteral("InsuranceCoverage"));
        InsuranceCoverage->setGeometry(QRect(70, 90, 110, 25));
        InsuranceCoverage->setInputMethodHints(Qt::ImhNone);
        label_40 = new QLabel(tab_2);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(10, 90, 60, 25));
        label_40->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        PremiumInsurancePremium = new QLineEdit(tab_2);
        PremiumInsurancePremium->setObjectName(QStringLiteral("PremiumInsurancePremium"));
        PremiumInsurancePremium->setGeometry(QRect(180, 90, 110, 25));
        PremiumInsurancePremium->setInputMethodHints(Qt::ImhNone);
        Description_2 = new QLineEdit(tab_2);
        Description_2->setObjectName(QStringLiteral("Description_2"));
        Description_2->setGeometry(QRect(70, 130, 621, 25));
        Description_2->setInputMethodHints(Qt::ImhNone);
        label_41 = new QLabel(tab_2);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(10, 130, 60, 25));
        tabWidget->addTab(tab_2, QString());
        Entry = new QPushButton(Form);
        Entry->setObjectName(QStringLiteral("Entry"));
        Entry->setGeometry(QRect(530, 590, 90, 40));
        Cancel = new QPushButton(Form);
        Cancel->setObjectName(QStringLiteral("Cancel"));
        Cancel->setGeometry(QRect(670, 590, 90, 40));

        retranslateUi(Form);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(Form);
    } // setupUi

    void retranslateUi(QWidget *Form)
    {
        Form->setWindowTitle(QApplication::translate("Form", "Form", nullptr));
        INSUR_LABEL->setText(QApplication::translate("Form", "\350\275\246\350\276\206\344\277\235\351\231\251\345\275\225\345\205\245", nullptr));
        label_2->setText(QApplication::translate("Form", "\346\212\225\344\277\235\346\227\245\346\234\237", nullptr));
        label_3->setText(QApplication::translate("Form", "\344\277\235\351\231\251\345\210\260\346\234\237", nullptr));
        label_4->setText(QApplication::translate("Form", "\346\211\277\344\277\235\345\205\254\345\217\270", nullptr));
        label_5->setText(QApplication::translate("Form", "\345\225\206\344\270\232\351\231\251\345\217\267", nullptr));
        label_6->setText(QApplication::translate("Form", "\344\272\244\345\274\272\351\231\251\345\217\267", nullptr));
        label_7->setText(QApplication::translate("Form", "\350\201\224\347\263\273\344\272\272", nullptr));
        label_8->setText(QApplication::translate("Form", "\350\201\224\347\263\273\347\224\265\350\257\235", nullptr));
        label_9->setText(QApplication::translate("Form", "\350\272\253\344\273\275\350\257\201\345\217\267", nullptr));
        label_10->setText(QApplication::translate("Form", "\347\273\217\345\212\236\344\272\272", nullptr));
        label_11->setText(QApplication::translate("Form", "\345\275\222\345\217\243\351\203\250\351\227\250", nullptr));
        label_12->setText(QApplication::translate("Form", "\347\274\264\347\272\263\347\212\266\345\206\265", nullptr));
        PaymentState->setItemText(0, QApplication::translate("Form", "\345\267\262\344\272\244", nullptr));
        PaymentState->setItemText(1, QApplication::translate("Form", "\346\234\252\344\272\244", nullptr));

        label_13->setText(QApplication::translate("Form", "\347\274\264\347\272\263\346\227\266\351\227\264", nullptr));
        PaymentMethod->setItemText(0, QApplication::translate("Form", "\347\216\260\351\207\221", nullptr));
        PaymentMethod->setItemText(1, QApplication::translate("Form", "\350\275\254\350\264\246", nullptr));
        PaymentMethod->setItemText(2, QApplication::translate("Form", "\346\224\257\344\273\230\345\256\235", nullptr));
        PaymentMethod->setItemText(3, QApplication::translate("Form", "\345\276\256\344\277\241", nullptr));

        label_14->setText(QApplication::translate("Form", "\344\273\230\350\264\271\346\226\271\345\274\217", nullptr));
        label_15->setText(QApplication::translate("Form", "\344\272\244\345\274\272\346\200\273\344\277\235\350\264\271", nullptr));
        label_16->setText(QApplication::translate("Form", "\345\225\206\344\270\232\346\200\273\344\277\235\350\264\271", nullptr));
        label_17->setText(QApplication::translate("Form", "\346\200\273\344\277\235\350\264\271", nullptr));
        label_18->setText(QApplication::translate("Form", "\344\272\244\345\274\272\344\274\230\346\203\240\346\257\224", nullptr));
        label_19->setText(QApplication::translate("Form", "\345\225\206\344\270\232\344\274\230\346\203\240\346\257\224", nullptr));
        label_20->setText(QApplication::translate("Form", "\344\272\244\345\274\272\345\272\224\346\224\266\350\264\271", nullptr));
        label_21->setText(QApplication::translate("Form", "\345\225\206\344\270\232\345\272\224\346\224\266\350\264\271", nullptr));
        label_22->setText(QApplication::translate("Form", "\346\200\273\345\272\224\346\224\266", nullptr));
        label_23->setText(QApplication::translate("Form", "\346\217\220\346\210\220\350\264\271\347\224\250", nullptr));
        label_24->setText(QApplication::translate("Form", "\350\275\246\344\270\273", nullptr));
        label_25->setText(QApplication::translate("Form", "\345\217\267\347\211\214", nullptr));
        label_26->setText(QApplication::translate("Form", "\350\275\246\346\236\266\345\217\267", nullptr));
        label_27->setText(QApplication::translate("Form", "\350\275\246\345\236\213", nullptr));
        label_28->setText(QApplication::translate("Form", "\345\217\221\345\212\250\346\234\272\345\217\267", nullptr));
        label_29->setText(QApplication::translate("Form", "\346\212\225\344\277\235\344\272\272", nullptr));
        label_30->setText(QApplication::translate("Form", "\345\223\201\347\211\214", nullptr));
        label_31->setText(QApplication::translate("Form", "\345\272\247\344\275\215\344\272\272\346\225\260", nullptr));
        label_32->setText(QApplication::translate("Form", "\350\242\253\344\277\235\351\231\251\344\272\272", nullptr));
        label_33->setText(QApplication::translate("Form", "\351\224\200\345\224\256\346\227\245\346\234\237", nullptr));
        label_34->setText(QApplication::translate("Form", "\346\226\260\350\275\246\350\264\255\347\275\256\344\273\267", nullptr));
        label_35->setText(QApplication::translate("Form", "\350\256\251\345\210\251\345\217\212\345\244\207\346\263\250", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("Form", "\350\275\246\350\276\206\344\277\241\346\201\257", nullptr));
        label_36->setText(QApplication::translate("Form", "\350\275\246\350\276\206\346\215\237\345\244\261\351\231\251", nullptr));
        label_37->setText(QApplication::translate("Form", "\347\254\254\344\270\211\350\264\243\344\273\273\351\231\251", nullptr));
        label_38->setText(QApplication::translate("Form", "\350\207\252\347\207\203\346\215\237\345\244\261\351\231\251", nullptr));
        label_39->setText(QApplication::translate("Form", "\345\210\222\347\227\225\351\231\251", nullptr));
        label_40->setText(QApplication::translate("Form", "\344\272\244\345\274\272\351\231\251", nullptr));
        label_41->setText(QApplication::translate("Form", "\345\244\207\346\263\250", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("Form", "\346\212\225\344\277\235\344\277\241\346\201\257", nullptr));
        Entry->setText(QApplication::translate("Form", "\345\275\225\345\205\245", nullptr));
        Cancel->setText(QApplication::translate("Form", "\345\217\226\346\266\210", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Form: public Ui_Form {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_INSUR_GUARANTEESLIP_H
